import Head from "next/head";
import Link from "next/link";
import DaySchedule from "../components/DaySchedule"

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const shifts = [
    { start: "09:15", end: "11:45", color: "#007bff" },
    { start: "13:00", end: "16:00", color: "#e44d25" },
    { start: "20:00", end: "22:45", color: "#e44d25" }
  ];
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <DaySchedule initialShifts={shifts}></DaySchedule>
      </main>
    </>
  );
}
